server:
  port: 8090

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}

tracker:
  url: ${TRACKER_URL:http://currency-tracker:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: telegram-bot

logging:
  level:
    org.telegram: INFO
